name: Dry Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Dry Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependecies
        run: npm ci

      - name: Build
        run: npm run build
