name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependecies
        run: npm ci

      - name: Generate migrations
        run: npm run db:generate

      - name: Run tests
        run: npm run test
